import * as fs from 'fs/promises';
import * as path from 'path';
import { scanSalesforceProject, SalesforceScanResult } from './salesforceScanner';

/**
 * Agent context file generator.
 * Compiles CodeLoop's deterministic knowledge (metadata scan, risk warnings,
 * test gaps, project rules, architecture decisions, coding standards) into
 * compact instruction files that OTHER agents read on every session:
 *   CLAUDE.md                          → Claude Code
 *   AGENTS.md                          → Codex / generic agents
 *   .github/copilot-instructions.md    → GitHub Copilot
 *
 * This saves those agents thousands of discovery tokens per session — the
 * project shape arrives pre-digested instead of being re-read from raw files.
 *
 * Files are updated through a managed block, so hand-written content outside
 * the block is always preserved.
 */

export const CONTEXT_TARGETS = ['CLAUDE.md', 'AGENTS.md', '.github/copilot-instructions.md'] as const;

const BLOCK_BEGIN = '<!-- CODELOOP:BEGIN — generated by CodeLoop AI. Do not edit inside this block; regenerate with "CodeLoop AI: Generate Agent Context Files". -->';
const BLOCK_END = '<!-- CODELOOP:END -->';

const MAX_WARNINGS = 10;
const MAX_MISSING_TESTS = 15;
const MAX_OBJECTS = 10;
const MAX_TRIGGERS = 10;
const MAX_FLOWS = 8;
const MAX_SECTION_CHARS = 2000;

export interface AgentContextResult {
  files: string[];
  content: string;
}

/** Insert or replace the managed block, preserving everything else. */
export function upsertManagedBlock(existing: string, block: string): string {
  const wrapped = `${BLOCK_BEGIN}\n${block.trim()}\n${BLOCK_END}`;
  if (!existing.trim()) {
    return `${wrapped}\n`;
  }
  const pattern = new RegExp(`${escapeRegExp(BLOCK_BEGIN)}[\\s\\S]*?${escapeRegExp(BLOCK_END)}`);
  if (pattern.test(existing)) {
    return existing.replace(pattern, wrapped);
  }
  return `${existing.trimEnd()}\n\n${wrapped}\n`;
}

/** Build the context markdown from scan results and memory files (pure). */
export function buildAgentContextMarkdown(
  scan: SalesforceScanResult,
  projectRules: string,
  decisions: string,
  standards: string
): string {
  const lines: string[] = [
    '# Salesforce Project Context (CodeLoop AI)',
    '',
    `_Generated ${new Date().toISOString()} — a pre-digested map of this project. Trust it for orientation; verify specifics in code._`,
    ''
  ];

  // -- Project shape ---------------------------------------------------------
  const c = scan.counts;
  lines.push(
    '## Project shape',
    '',
    `Salesforce DX project: ${c.apexClasses} Apex classes, ${c.triggers} triggers, ${c.lwcComponents} LWC components, ${c.flows} flows, ${c.visualforcePages} Visualforce pages, ${c.objects} objects, ${c.permissionSets} permission sets, ${c.customLabels} custom labels, ${c.customMetadata} custom metadata records.`,
    ''
  );

  // -- Architecture patterns ---------------------------------------------------
  const p = scan.patterns;
  const layer = (label: string, names: string[]) =>
    names.length ? `- ${label} (${names.length}): ${names.slice(0, 12).join(', ')}${names.length > 12 ? ' …' : ''}` : '';
  const layers = [
    layer('Selectors', p.selectors),
    layer('Services', p.services),
    layer('Handlers', p.handlers),
    layer('Domains', p.domains),
    layer('REST resources', p.restResources),
    layer('Batchables', p.batchables),
    layer('Queueables', p.queueables),
    layer('Schedulables', p.schedulables)
  ].filter(Boolean);
  lines.push('## Architecture patterns in use', '');
  lines.push(...(layers.length ? layers : ['- No layered pattern classes detected — check before assuming a framework.']));
  lines.push('');

  // -- Key objects / triggers / flows ------------------------------------------
  if (scan.objectSummaries.length) {
    lines.push('## Key objects', '');
    for (const o of scan.objectSummaries.slice(0, MAX_OBJECTS)) {
      lines.push(`- ${o.apiName}: ${o.fieldCount} fields, ${o.recordTypeCount} record types, ${o.validationRuleCount} validation rules`);
    }
    lines.push('');
  }
  if (scan.triggerSummaries.length) {
    lines.push('## Triggers', '');
    for (const t of scan.triggerSummaries.slice(0, MAX_TRIGGERS)) {
      lines.push(`- ${t.name} on ${t.objectName} (${t.events})`);
    }
    lines.push('');
  }
  if (scan.flowSummaries.length) {
    lines.push('## Flows', '');
    for (const f of scan.flowSummaries.slice(0, MAX_FLOWS)) {
      lines.push(`- ${f.apiName}: object=${f.triggerObject}, type=${f.processType}, status=${f.status}`);
    }
    lines.push('');
  }

  // -- Known risks ---------------------------------------------------------------
  if (scan.warnings.length) {
    lines.push('## Known risks (heuristic scan — verify before fixing)', '');
    lines.push(...scan.warnings.slice(0, MAX_WARNINGS).map(w => `- ${w}`));
    if (scan.warnings.length > MAX_WARNINGS) {
      lines.push(`- … ${scan.warnings.length - MAX_WARNINGS} more in .agent-memory/project-summary.md`);
    }
    lines.push('');
  }

  // -- Test coverage ----------------------------------------------------------------
  lines.push('## Test coverage', '');
  lines.push(`- Classes with a matching test class: ${scan.testMapping.testedCount}`);
  lines.push(`- Classes MISSING tests: ${scan.testMapping.missingTests.length}${scan.testMapping.missingTests.length ? ` (e.g. ${scan.testMapping.missingTests.slice(0, MAX_MISSING_TESTS).join(', ')}${scan.testMapping.missingTests.length > MAX_MISSING_TESTS ? ' …' : ''})` : ''}`);
  lines.push('');

  // -- Standards / rules / decisions ---------------------------------------------------
  if (standards.trim()) {
    lines.push('## Coding standards (follow these)', '', clip(stripHeading(standards), MAX_SECTION_CHARS), '');
  }
  if (projectRules.trim() && !isDefaultMemoryFile(projectRules)) {
    lines.push('## Project rules', '', clip(stripHeading(projectRules), MAX_SECTION_CHARS), '');
  }
  if (decisions.trim() && !isDefaultMemoryFile(decisions)) {
    lines.push('## Recent architecture decisions (stay consistent)', '', clip(tail(stripHeading(decisions), MAX_SECTION_CHARS), MAX_SECTION_CHARS), '');
  }

  lines.push(
    '## Working in this project',
    '',
    '- Full metadata details: .agent-memory/project-summary.md',
    '- Salesforce instructions, roles, and skills: .codeloop/',
    '- Prefer targeted edits over full-file rewrites; read related test classes before changing Apex.'
  );

  return lines.join('\n');
}

/** Scan the project, build the context, and upsert it into the chosen targets. */
export async function generateAgentContextFiles(
  workspaceRoot: string,
  targets: string[]
): Promise<AgentContextResult> {
  const scan = await scanSalesforceProject(workspaceRoot);
  const [rules, decisions, standards] = await Promise.all([
    readSafe(path.join(workspaceRoot, '.agent-memory', 'project-rules.md')),
    readSafe(path.join(workspaceRoot, '.agent-memory', 'salesforce-decisions.md')),
    readSafe(path.join(workspaceRoot, '.codeloop', 'instructions', 'salesforce-instructions.md'))
  ]);

  const content = buildAgentContextMarkdown(scan, rules, decisions, standards);
  const written: string[] = [];

  for (const target of targets) {
    const full = path.join(workspaceRoot, target);
    await fs.mkdir(path.dirname(full), { recursive: true });
    const existing = await readSafe(full);
    await fs.writeFile(full, upsertManagedBlock(existing, content), 'utf8');
    written.push(target);
  }

  return { files: written, content };
}

// ---------------------------------------------------------------------------

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function clip(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max)}\n…(truncated)` : text;
}

function tail(text: string, max: number): string {
  return text.length > max ? text.slice(-max) : text;
}

/** Drop the H1 line so nested headings compose cleanly. */
function stripHeading(text: string): string {
  return text.replace(/^#\s.*\n+/, '').trim();
}

/** True when a memory file still only has its default placeholder content. */
function isDefaultMemoryFile(text: string): boolean {
  const body = stripHeading(text);
  return body.length < 120 && /add project-specific rules|architecture and design decisions made during agent tasks/i.test(body);
}

async function readSafe(p: string): Promise<string> {
  try {
    return await fs.readFile(p, 'utf8');
  } catch {
    return '';
  }
}
